services:
  upload-server:
    build: ./app
    container_name: upload-app
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/uploads
      - ./app:/app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8089:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./uploads:/uploads
    depends_on:
      - upload-server
